### PR TITLE
Fixed hanging program. Should exit right away when QUIT is called.

### PR DESCRIPTION
**Pull request by MusicDev33**

### CODE REVIEW

**Comment by najarvis** [comment]
Was it really 'hanging' though? I use this in my projects and this way it closes cleanly and not in the middle of a while loop.

**Comment by najarvis** [comment]
Nevermind, I forgot to put a pygame.quit() at the end on my side. I must've missed that on accident. Thank you.

**Comment by najarvis** [comment]
Let me know if it still "hangs"

**Comment by MusicDev33** [comment]
Yeah it still hangs. sys.exit() should do it.

**Comment by najarvis** [comment]
Are you on IDLE? can you describe or show a picture of it hanging? for me it closes cleanly. I'm fine with adding a sys.exit(), but I was wondering what the problem is.

**Comment by MusicDev33** [comment]
You know, I think IDLE might be the problem. What IDE do you use?

edit- Yep. IDLE is the problem. Apparently TKinter and PyGame main loops don't really go well together...

**Comment by najarvis** [comment]
I code in the terminal with VIM and just launch straight from the command line. no IDE.

**Comment by MusicDev33** [comment]
Yea I'll probably just run from command line. Runs alright from cmd.

**Comment by najarvis** [comment]
All right, thank you for catching that though! I'm not sure why IDLE does that.

**Comment by MusicDev33** [comment]
Yea IDLE's just weird. I'm probably going to switch IDE's pretty soon

**Pull request closed without merging**
